slack:
  token: xoxb-3040372380436-3038082325986-fytO5EfTrCDseIXRtu1fBvDM1234
  socket_token: xapp-1-A03143484QK-3035174483685-368fd90531a773f42193fe12fcd7f4f6f37bd6daa889dd724a16f3f40c458cd61234
  debug: true

jenkins:
  host: "http://localhost:8080"
  username: shivin  
  password: shivin
  jobs:
    test:
      parameters:
        - name: BRANCH
          default: master
          type: string

crons:
  - schedule: "* 10 * * *"
    channel: "#general"
    commands:
      - weather
      - newsfeed
      - celebrations

open_weather:
  api_key: a8c44e038e53815ee892e48dcdca2c3e
  location: Bengaluru

logger:
  level: debug
  file: ./bot.log

timezone: UTC

server:
  base_url: "http://localhost:8000"
  timeout: 10
  max_conns_per_host: 3
